default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "be_api_development") %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST", "be_api_test") %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
